OUTFILENAME=decimator
#OUTPATH=../Debug
OUTPATH=.
OUTFILE=$(OUTPATH)/$(OUTFILENAME)
INPATH=../src

SRC=$(INPATH)/*.c $(INPATH)/*.cpp
HRD=$(INPATH)/*.h $(INPATH)/*.hpp
KERNELS=kernels.cl

PLATFORM=-m32
CFLAGS=$(PLATFORM) -DLINUX -I$(AMDAPPSDKROOT)/include/

LDFLAGS=-L$(AMDAPPSDKROOT)/lib/x86
LIBS=-lOpenCL -lGL -lGLU -lGLEW -lglut

CPPSOURCES=camera.cpp configuration.cpp decimator.cpp decimatorDataValidators.cpp decimatorIndependentPoints.cpp decimatorPrepareData.cpp decimatorSort.cpp glut_callbacks.cpp main.cpp object.cpp plyobject.cpp rply.c scene.cpp
#HEDAERS=camera.hpp configuration.hpp decimator.hpp glut_callbacks.hpp plyobject.hpp point3.hpp rply.h cl.hpp object.hpp 
OBJECTS=$(addprefix $(OUTPATH)/,$(subst .c,.o,$(subst .cpp,.o,$(CPPSOURCES))))

all: build copy_kernels

build:link

link: $(OBJECTS)
	g++ $(PLATFORM) $(LDFLAGS) $(OBJECTS) $(LIBS) -o $(OUTFILE)

$(OUTPATH)/%.o:$(INPATH)/%.c
	gcc -c $(CFLAGS) $< -o $@
	
$(OUTPATH)/%.o:$(INPATH)/%.cpp
	g++ -c $(CFLAGS) $< -o $@
	
copy_kernels:$(INPATH)/$(KERNELS)
	cp $(INPATH)/$(KERNELS) $(OUTPATH)/$(KERNELS)
	
clean:
	rm -f $(OBJECTS)
#	rm $(OUTPATH)/$(OUTFILE)


